spring:
  boot:
    admin:
      client:   #服务监控客户端
        url: http://127.0.0.1:8771
  zipkin: #提交链路跟踪
    base-url: http://127.0.0.1:9411    #链路跟踪监控地址
    enabled: true
  application:
    name: eureka-gateway

server:
  port: 8770

zuul:   #网关路由配置
  routes:
    consumer-user:
      path: /api-a/**  #路由配置
      serviceId: CONSUMER-USER

eureka:  #向eureka注册服务
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #eureka地址

