spring:
  application:
    name: eureka-gateway
server:
  port: 8770
zuul:
  routes:
    consumer-user:
      path: /api-a/**
      serviceId: PROVIDER-TICKT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

