eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://127.0.0.1:9411 #开启链路跟踪
    enabled: true
  application:
    name: springcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zuihou57124/springcloud-config.git
          username: 1545409483@qq.com
          password: 4188qinwei
          search-paths: config
  boot:
    admin:
      client:   #服务监控客户端
        url: http://127.0.0.1:8771
server:
  port: 8888
