server:
  port: 8771 #端口

spring:
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  application:
    name: cloud-admin-server #服务监控者应用名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
